// problematic
export component MainWindow inherits Rectangle {
    width: 800px;
    height: 480px;
    background: white;

    VerticalLayout {
        HorizontalLayout {
            t := Text {
                width: 60px;
                font-size: 18px;
                text: "y";
            }

            Rectangle {
                width: 40px;
                height: 40px;
                Rectangle {
                    background: red;
                    width: 20px;
                    height: 20px;
                }
            }
        }

        Rectangle {
            x: 0px;
            height: 50px;
            width: 100px;
            background: yellow;

            TouchArea {
                clicked => {
                    t.text = t.text + "x";
                }
            }
        }
    }
}