// no problems with rendering
export component MainWindow inherits Rectangle {
    width: 800px;
    height: 480px;
    background: white;

    t := Text {
        x: 0;
        y: 0;
        width: 60px;
        font-size: 18px;
        text: "y";
    }

    Rectangle {
        x: 60px;
        y: 0px;
        width: 40px;
        height: 40px;
        Rectangle {
            background: red;
            width: 20px;
            height: 20px;
        }
    }

    Rectangle {
        x: 0px;
        y: 40px;
        height: 50px;
        width: 100px;
        background: yellow;

        TouchArea {
            clicked => {
                t.text = t.text + "x";
            }
        }
    }
}